name: matlab

env:
  CTEST_NO_TESTS_ACTION: error
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_PARALLEL_LEVEL: 0

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci-matlab.yml"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  unix:

    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
        matlab: [R2024b]

    runs-on: ${{ matrix.os }}

    env:
      FC: gfortran-14

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.matlab }}
        cache: true

    - uses: actions/checkout@v4

    - name: Lint task
      uses: matlab-actions/run-build@v2
      with:
        tasks: check

    - name: Test task
      uses: matlab-actions/run-build@v2
      with:
        tasks: test


  msys2:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: msys2/setup-msys2@v2
      id: msys2
      with:
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ steps.msys2.outputs.msys2-location }}/ucrt64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024b
        cache: true

    - uses: actions/checkout@v4

    - name: Lint task
      uses: matlab-actions/run-build@v2
      with:
        tasks: check

    - name: Test task
      uses: matlab-actions/run-build@v2
      with:
        tasks: test
